// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerApp.Database;

#nullable disable

namespace ServerApp.Migrations
{
    [DbContext(typeof(TicketsDbContext))]
    [Migration("20240223205252_mehdi-tag-test")]
    partial class mehditagtest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.ResponseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("Shared.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CSharp"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DotNet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blazor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 5,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 7,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 8,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 10,
                            Name = "NoSQL"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 14,
                            Name = "MachineLearning"
                        },
                        new
                        {
                            Id = 15,
                            Name = "ArtificialIntelligence"
                        },
                        new
                        {
                            Id = 16,
                            Name = "DataScience"
                        },
                        new
                        {
                            Id = 17,
                            Name = "WebDevelopment"
                        },
                        new
                        {
                            Id = 18,
                            Name = "MobileDevelopment"
                        },
                        new
                        {
                            Id = 19,
                            Name = "GameDevelopment"
                        },
                        new
                        {
                            Id = 20,
                            Name = "CloudComputing"
                        },
                        new
                        {
                            Id = 21,
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 23,
                            Name = "GCP"
                        },
                        new
                        {
                            Id = 24,
                            Name = "DevOps"
                        },
                        new
                        {
                            Id = 25,
                            Name = "CI_CD"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Agile"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Security"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = 30,
                            Name = "IoT"
                        },
                        new
                        {
                            Id = 31,
                            Name = "AR_VR"
                        },
                        new
                        {
                            Id = 32,
                            Name = "UI_UX"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Algorithms"
                        },
                        new
                        {
                            Id = 34,
                            Name = "DataStructures"
                        },
                        new
                        {
                            Id = 35,
                            Name = "DesignPatterns"
                        },
                        new
                        {
                            Id = 36,
                            Name = "FunctionalProgramming"
                        },
                        new
                        {
                            Id = 37,
                            Name = "ObjectOrientedProgramming"
                        });
                });

            modelBuilder.Entity("Shared.Models.TicketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("TagModelTicketModel", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("TagModelTicketModel");
                });

            modelBuilder.Entity("Shared.Models.ResponseModel", b =>
                {
                    b.HasOne("Shared.Models.TicketModel", "Ticket")
                        .WithMany("Responses")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TagModelTicketModel", b =>
                {
                    b.HasOne("Shared.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.TicketModel", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.TicketModel", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
